In [1]:
from numpy.random import seed
seed(888)
import tensorflow as tf
tf.random.set_seed(404)

# imports

In [2]:
import os
import numpy as np
from time import strftime
from PIL import Image




# constants

In [3]:
X_TRAIN_PATH='F:/python/MNIST/digit_xtrain.csv'
Y_TRAIN_PATH='F:/python/MNIST/digit_ytrain.csv'
X_TEST_PATH='F:/python/MNIST/digit_xtest.csv'
Y_TEST_PATH='F:/python/MNIST/digit_ytest.csv'
LOGGING_PATH='tensorboard_mnist_digit_logs/'
NR_CLASSES=10
VAL_DATA_SIZE=10000
IMG_HGT=28
IMG_WDH=28
NR_CHANNEL=1
TOTAL_INPUT=IMG_HGT*IMG_WDH*NR_CHANNEL

# load data

In [4]:
%%time
x_train_all=np.loadtxt(X_TRAIN_PATH, delimiter=',',dtype=int)
x_train_all.shape

Wall time: 45.8 s


(60000, 784)

In [5]:
%%time
y_train_all=np.loadtxt(Y_TRAIN_PATH, delimiter=',',dtype=int)
y_train_all.shape

Wall time: 372 ms


(60000,)

In [6]:
%%time
x_test=np.loadtxt(X_TEST_PATH, delimiter=',',dtype=int)

Wall time: 7.52 s


In [7]:
%%time
y_test=np.loadtxt(Y_TEST_PATH, delimiter=',',dtype=int)

Wall time: 101 ms


In [8]:
x_train_all.shape

(60000, 784)

In [9]:
x_train_all[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [10]:
y_train_all.shape

(60000,)

In [11]:
y_train_all[:5]

array([5, 0, 4, 1, 9])

# data preprocessing

In [12]:
x_train_all,x_test=x_train_all/255,x_test/255

## convert target values to hot encoding

In [13]:
values=y_train_all[:5]
values

array([5, 0, 4, 1, 9])

In [14]:
np.eye(10)[values] # values acts as index array each num in values pills out rows from np.eye(10)corresponds to num from values
                    # eg: values[0] is 5 it pulls out 6th row from np.eye(10) as index starts from 0

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
y_train_all=np.eye(NR_CLASSES)[y_train_all]
y_train_all[:5]


array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
y_test = np.eye(NR_CLASSES)[y_test]
y_test.shape

(10000, 10)

In [18]:
x_val=x_train_all[:VAL_DATA_SIZE]
y_val=y_train_all[:VAL_DATA_SIZE]
x_val.shape

(10000, 784)

In [19]:
x_train=x_train_all[VAL_DATA_SIZE:]
y_train=y_train_all[VAL_DATA_SIZE:]
x_train.shape

(50000, 784)

# Setup Tensorflow graph

In [20]:
tf.compat.v1.disable_eager_execution()
X=tf.compat.v1.placeholder(tf.float32,shape=[None,TOTAL_INPUT],name='x')
Y=tf.compat.v1.placeholder(tf.float32,shape=[None,NR_CLASSES],name='labels')



# hyper parameters

In [21]:
nr_epochs=50
learning_rate=1e-3 #.0001

n_hidden1=512
n_hidden2=64

In [22]:
def setup_layer(input,weight_dim,bias_dim,name):
    with tf.name_scope(name):
        initial_w=tf.compat.v1.random.truncated_normal(shape=weight_dim,stddev=0.1,seed=42)
        w=tf.Variable(initial_value=initial_w,name='W')
        initial_b=tf.constant(value=0.0,shape=bias_dim)
        b=tf.Variable(initial_value=initial_b,name='B')
        layer_in=tf.matmul(input,w)+b
        if name=='out':
            layer_out=tf.nn.softmax(layer_in)
        else:
            layer_out=tf.nn.relu(layer_in)


        tf.compat.v1.summary.histogram('weights', w)
        tf.compat.v1.summary.histogram('biases', b)

        return layer_out

    

In [23]:
# def setup_layer(input, weight_dim, bias_dim, name):
    
#     with tf.name_scope(name):
#         initial_w = tf.compat.v1.random.truncated_normal(shape=weight_dim, stddev=0.1, seed=42)
#         w = tf.Variable(initial_value=initial_w, name='W')

#         initial_b = tf.constant(value=0.0, shape=bias_dim)
#         b = tf.Variable(initial_value=initial_b, name='B')

#         layer_in = tf.matmul(input, w) + b
        
#         if name=='out':
#             layer_out = tf.nn.softmax(layer_in)
#         else:
#             layer_out = tf.nn.relu(layer_in)
        
#         tf.summary.histogram('weights', w)
#         tf.summary.histogram('biases', b)
        
#         return layer_out

In [24]:
layer1=setup_layer(X,weight_dim=[TOTAL_INPUT,n_hidden1],bias_dim=[n_hidden1],name='hidden1')

layer_drop = tf.nn.dropout(layer1, rate=0.2, name='dropout_layer')

layer2=setup_layer(layer_drop,weight_dim=[n_hidden1,n_hidden2],bias_dim=[n_hidden2],name='hidden2')

output=setup_layer(layer2,weight_dim=[n_hidden2,NR_CLASSES],bias_dim=[NR_CLASSES],name='out')

model_name = f'{n_hidden1}-DO-{n_hidden2} LR{learning_rate} E{nr_epochs}'

# Tensorboard setup

In [25]:
folder_name=f'{model_name} at{strftime("%H %M")}'
directory=os.path.join(LOGGING_PATH,folder_name)
try:
    os.makedirs(directory)
except OSError as exception:
    print(exception.strerror)
else:
    print('successfully created directory')

successfully created directory


# Loss, Optimisation & Metrics

# loss

In [26]:
with tf.name_scope('loss_calc'):
    loss=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y,logits=output))

# optimiser

In [27]:
with tf.name_scope('optimisation'):
    optimiser=tf.compat.v1.train.AdamOptimizer(learning_rate=learning_rate)
    train_step=optimiser.minimize(loss)

# accuracy

In [28]:
with tf.name_scope('accuracy'):
    correct_pred=tf.equal(tf.argmax(output,axis=1),tf.argmax(Y,axis=1))
    accuracy=tf.reduce_mean(tf.cast(correct_pred,tf.float32))

In [29]:
with tf.name_scope('performance'):
    tf.compat.v1.summary.scalar('accuracy',accuracy)
    tf.compat.v1.summary.scalar('cost',loss)


In [30]:
with tf.name_scope('show_image'):
    x_image = tf.reshape(X, [-1, 28, 28, 1])
    tf.compat.v1.summary.image('image_input', x_image, max_outputs=4)

# Run session

In [31]:
sess=tf.compat.v1.Session()


### setup filewriter & merge summaries

In [32]:
merged_summary = tf.compat.v1.summary.merge_all()

train_writer = tf.compat.v1.summary.FileWriter(directory + '/train')
train_writer.add_graph(sess.graph)

validation_writer = tf.compat.v1.summary.FileWriter(directory + '/validation')

In [33]:
init=tf.compat.v1.global_variables_initializer()
sess.run(init)

# Batching the data

In [34]:
size_of_batch=1000
num_examples=y_train.shape[0]
nr_iterations=int(num_examples/size_of_batch)
index_in_epoch=0

In [35]:
def next_batch(batch_size,data,labels):
    global num_examples
    global index_in_epoch # referencing value outside the function
    start=index_in_epoch
    index_in_epoch+=batch_size
    if index_in_epoch>num_examples:
        start=0
        index_in_epoch=batch_size
    end=index_in_epoch
    return data[start:end],labels[start:end]
    
        

# training loop

In [36]:
for epochs in range(nr_epochs):
    for i in range(nr_iterations):
        
        batch_x,batch_y=next_batch(batch_size=size_of_batch,data=x_train,labels=y_train)
        feed_dictionary={X:batch_x,Y:batch_y}
        
        sess.run(train_step,feed_dict=feed_dictionary)
        
    batch_accuracy,s=sess.run(fetches=[accuracy,merged_summary], feed_dict=feed_dictionary)
    train_writer.add_summary(s,epochs)
    print(f'Epoch {epochs} \t| Trainig Accuracy ={batch_accuracy}')
    
    #validation
    
    summary=sess.run(fetches=merged_summary,feed_dict={X:x_val,Y:y_val})
    validation_writer.add_summary(summary,epochs)
    
 

print('DONE TRAINING !!')
     

Epoch 0 	| Trainig Accuracy =0.8510000109672546
Epoch 1 	| Trainig Accuracy =0.8650000095367432
Epoch 2 	| Trainig Accuracy =0.8690000176429749
Epoch 3 	| Trainig Accuracy =0.8700000047683716
Epoch 4 	| Trainig Accuracy =0.8730000257492065
Epoch 5 	| Trainig Accuracy =0.8740000128746033
Epoch 6 	| Trainig Accuracy =0.9760000109672546
Epoch 7 	| Trainig Accuracy =0.9789999723434448
Epoch 8 	| Trainig Accuracy =0.9789999723434448
Epoch 9 	| Trainig Accuracy =0.9860000014305115
Epoch 10 	| Trainig Accuracy =0.9829999804496765
Epoch 11 	| Trainig Accuracy =0.9869999885559082
Epoch 12 	| Trainig Accuracy =0.9860000014305115
Epoch 13 	| Trainig Accuracy =0.984000027179718
Epoch 14 	| Trainig Accuracy =0.9879999756813049
Epoch 15 	| Trainig Accuracy =0.9890000224113464
Epoch 16 	| Trainig Accuracy =0.9879999756813049
Epoch 17 	| Trainig Accuracy =0.9860000014305115
Epoch 18 	| Trainig Accuracy =0.9900000095367432
Epoch 19 	| Trainig Accuracy =0.9879999756813049
Epoch 20 	| Trainig Accuracy =0

# make prediction

In [37]:
img=Image.open('F:/python/MNIST/test_img.png')
img

In [38]:
black_white=img.convert('L')


In [39]:
img_array=np.invert(black_white)
img_array.shape

(28, 28)

In [40]:
test_img=img_array.ravel()

In [41]:
prediction=sess.run(fetches=tf.argmax(output),feed_dict={X:[test_img]})
print(f'prediction for the test image is {prediction}')

prediction for the test image is [0 0 0 0 0 0 0 0 0 0]


In [42]:
accuracy_test=sess.run(fetches=accuracy,feed_dict={X:x_test,Y:y_test})
print(f'Accuracy of test data prediction is {accuracy_test:.2%}')

Accuracy of test data prediction is 97.74%


# reset for next run

In [43]:
train_writer.close()
validation_writer.close()
sess.close()
tf.compat.v1.reset_default_graph()